### ISSUE TITLE
Samsung case 2

### ISSUE THREAD

**Issue by TrubnikovGI** [TrubnikovGI/OSiTP2020#4]
добавил код программы из кейса 2

**Comment by justjune** [comment]
А почему я вас не вижу на сайте Самсунг?

**Comment by TrubnikovGI** [comment]
Меня в самсунге не добавили в группу, когда данная проблема решится будет видно что я все тесты для первых двух кейсов сделал + я выложил код для [кейса 1](https://github.com/TrubnikovGI/OSiTP2020/blob/main/Case1(samsung%20academ).txt) его я сделал на паре(22.10.2021), сейчас выкладываю чтобы было видно, что сделал. Код для [кейса 2](https://github.com/TrubnikovGI/OSiTP2020/blob/main/Case2(samsung%20academ).txt) выложен 29.10.2021

**Comment by justjune** [comment]
См. Успеваемость.
