### ISSUE TITLE
mqtt

### ISSUE THREAD

**Issue by TrubnikovGI** [TrubnikovGI/OSiTP2020#5]
отправил данные о температуре и влажности с издателя (ресурс [MQTTX](https://mqttx.app/)) на брокера (ресурс [Rightech](https://dev.rightech.io)). В репозитории [картинка1](https://github.com/TrubnikovGI/OSiTP2020/blob/main/1.png) это установка связи между издателем и брокером, [картинка2](https://github.com/TrubnikovGI/OSiTP2020/blob/main/2.png) это отправка сообщения

**Comment by justjune** [comment]
См. Успеваемость.................
